name: "headless CI/CD Pipeline"

on:
  push:
    branches:
      - main
    paths:
      - "headless/**"
  pull_request:
    branches:
      - main
    paths:
      - "headless/**"
  workflow_dispatch:
    inputs:
      deploy:
        description: "Manually trigger deploy to Firebase (set true to activate)"
        required: false
        default: "false"

defaults:
  run:
    working-directory: ./headless

jobs:
  headless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./headless/package-lock.json

      - name: Install Front-end Dependencies
        run: npm ci

      - name: Lint Front-end
        run: npm run lint

      - name: Set up Variables && Build Front-end
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          API_URL: https://35-fit-nest-api-production.up.railway.app
          # API_URL: https://35-fit-api-production.up.railway.app
          NODE_ENV: ${{ vars.NODE_ENV }}
        run: npm run build

      - name: Deploy Front-end to Firebase
        if: contains(github.event.head_commit.message, '[d-headless]') || github.event.inputs.deploy == 'true'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run firebase-deploy
