name: "CI: Install, Lint (with Prettier), Build, and Conditional Firebase Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "functions/**"
      - "headless/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: "Manually trigger deploy to Firebase (set true to activate)"
        required: false
        default: "false"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # Install API
      - name: Use Node.js
        # if: contains(github.event.head_commit.message, '[run-api]')
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json

      - name: Set up Railway Environment Variables
        # if: contains(github.event.head_commit.message, '[run-api]')
        run: |
          echo "PGHOST=${{ secrets.PGHOST }}" >> $GITHUB_ENV
          echo "PGPORT=${{ secrets.PGPORT }}" >> $GITHUB_ENV
          echo "PGUSER=${{ secrets.PGUSER }}" >> $GITHUB_ENV
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> $GITHUB_ENV
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Install API Dependencies
        # if: contains(github.event.head_commit.message, '[run-api]')
        working-directory: ./api
        run: npm install --frozen-lockfile

      # Install Cloud Firebase Functions
      - name: Use Node.js
        # if: contains(github.event.head_commit.message, '[run-functions]')
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ./functions/package-lock.json

      - name: Install dependencies for functions
        # if: contains(github.event.head_commit.message, '[run-functions]')
        run: |
          cd functions
          npm install --frozen-lockfile

      # Deploy functions, triggers the error, require a new pay plan
      - name: Deploy functions to Firebase
        if: contains(github.event.head_commit.message, '[deploy-functions]')
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions

      - name: Serve functions
        if: contains(github.event.head_commit.message, '[deploy-functions]')
        run: |
          cd functions
          npm run serve

      # Install Front-end
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ./headless/package-lock.json

      - name: Install Front-end Dependencies
        working-directory: ./headless
        run: npm install --frozen-lockfile

      - name: Lint Front-end
        working-directory: ./headless
        run: npm run lint # script, combined with prettier-check in .eslintrc.cjs as 'plugin:prettier/recommended'

      - name: Set up Variables && Build Front-end
        working-directory: ./headless
        env:
          API_URL: ${{ secrets.API_URL }}
        run: npm run build

      # Determine if deployment should be triggered
      - name: Determine Deployment Trigger
        id: deployment_trigger
        run: |
          if [[ "${{ github.event.inputs.deploy }}" == "true" ]]; then
            echo "DEPLOY_TRIGGERED=true" >> $GITHUB_ENV
          elif git log -1 --pretty=%B | grep -q '\[deploy\]'; then
            echo "DEPLOY_TRIGGERED=true" >> $GITHUB_ENV
          else
            echo "DEPLOY_TRIGGERED=false" >> $GITHUB_ENV
          fi

      # Deploy Front-end to Firebase if triggered
      - name: Deploy Front-end to Firebase
        if: env.DEPLOY_TRIGGERED == 'true'
        working-directory: ./headless
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run firebase-deploy
