name: 'CI: Install, Build, Lint (with Prettier) and Conditional Firebase Deploy'

on: [push, pull_request]

defaults:
  run:
    working-directory: .

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version regardless of what is specified in the `.nvmrc` file
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --frozen-lockfile

      - name: Build Project
        run: npm run build # Runs script in package.json

      # - name: Run `prettier`
      #   run: npm run prettier-check # Runs script in package.json

      - name: Run `ESLint`
        run: npm run lint # Runs script in package.json, combined with prettier-check in .eslintrc.cjs as 'plugin:prettier/recommended'

      - name: Check for [deploy] in commit message
        id: check_deploy
        run: |
          if git log -1 --pretty=%B | grep -q '\[deploy\]'; then
            echo "DEPLOY_TRIGGERED=true" >> $GITHUB_ENV
          else
            echo "DEPLOY_TRIGGERED=false" >> $GITHUB_ENV
          fi

      - name: Deploy to Firebase
        if: env.DEPLOY_TRIGGERED == 'true'
        run: npm run firebase-deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
