name: "CI: Install, Lint (with Prettier), Build, and Conditional Firebase Deploy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: "Manually trigger deploy to Firebase (set true to activate)"
        required: false
        default: "false"

defaults:
  run:
    working-directory: .

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      # Install dependencies for front-end
      - name: Install Front-end Dependencies
        working-directory: ./headless
        run: npm install --frozen-lockfile

      # Lint front-end
      - name: Lint Front-end
        working-directory: ./headless
        run: npm run lint # Runs script in package.json, combined with prettier-check in .eslintrc.cjs as 'plugin:prettier/recommended'

      # Build front-end
      - name: Build Front-end
        working-directory: ./headless
        run: npm run build # Runs script in package.json

      # # Install dependencies for API
      # - name: Install API Dependencies
      #   working-directory: ./api
      #   run: npm install --frozen-lockfile

      # # Lint API
      # - name: Lint API
      #   working-directory: ./api
      #   run: npm run lint

      # Determine if deployment should be triggered
      - name: Determine Deployment Trigger
        id: deployment_trigger
        run: |
          if [[ "${{ github.event.inputs.deploy }}" == "true" ]]; then
            echo "DEPLOY_TRIGGERED=true" >> $GITHUB_ENV
          elif git log -1 --pretty=%B | grep -q '\[deploy\]'; then
            echo "DEPLOY_TRIGGERED=true" >> $GITHUB_ENV
          else
            echo "DEPLOY_TRIGGERED=false" >> $GITHUB_ENV
          fi

      # Deploy to Firebase if triggered
      - name: Deploy to Firebase
        if: env.DEPLOY_TRIGGERED == 'true'
        working-directory: ./headless
        run: npm run firebase-deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
