name: "CI/CD Pipeline for Nest.js App"

on:
  push:
    branches:
      - main
    paths:
      - "nest-api/**"
  pull_request:
    branches:
      - main
    paths:
      - "nest-api/**"

defaults:
  run:
    working-directory: nest-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build project
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test:cov

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -sSL https://cli.railway.app/install.sh | sh
          railway up --ci
